# Generated by Django 3.1.1 on 2020-09-09 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dolphin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_photo',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detail',
            name='brand',
            field=models.CharField(default='no detail brand', max_length=100),
        ),
        migrations.AlterField(
            model_name='detail',
            name='materials',
            field=models.CharField(default='no detail materials', max_length=100),
        ),
        migrations.AlterField(
            model_name='detail',
            name='measurements',
            field=models.CharField(default='no detail measurements', max_length=100),
        ),
        migrations.AlterField(
            model_name='detail',
            name='styles',
            field=models.CharField(default='no detail styles', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='no item name', max_length=100),
        ),
    ]
